#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

ZPREZTODIR="${ZDOTDIR:-$HOME}/.zprezto"

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi

# Customize to your needs...
